name: Sahaya
description: "Your disaster management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_config:
  telephony:
  permission_handler:
  google_fonts:
  font_awesome_flutter:
  intl_phone_field:
  url_launcher:
  shared_preferences:
  google_maps_flutter:
  geolocator: 
  custom_sliding_segmented_control:
  material_segmented_control:
  modal_bottom_sheet:
  flutter_svg:
  http:
  flutter_local_notifications:
  timezone:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  internet_connection_checker: ^0.0.1


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/
    - assets/background/
    - assets/maps/
    - assets/maps/markers/
    - assets/weatherData.json

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"
